### ISSUE TITLE
Average and marginal rates on corporations

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-Core#260]
@salimfurth notes that one might want to distinguish between the average and marginal rates faced by businesses.  These rates are often very different.  

This issue is to discuss the best way to incorporate differential average and marginal rates in OG-USA, including how the rates might be calibrated.

**Comment by salimfurth** [comment]
@jdebacker, I should have some time to work on this topic this week. Have you taken a theoretical poke at it yet? I'll dig a little today and follow up in this space.

**Comment by jdebacker** [comment]
I haven't thought too much more on this.  

Basically taxes are implemented by marking after-tax profits:

(1-\tau)(AK^{\alpha}l^{1-\alpha}-wL) - (r + \delta -\delta^{\tau})K,

where \tau is the marginal rate on corporate income and \delta^{\tau} is the rate of depreciation for tax purposes.

One way to incorporate an average rate would be to make this equation:
\tau^{avg}[(1-\tau)(AK^{\alpha}l^{1-\alpha}-wL) - (r + \delta -\delta^{\tau})K],

where \tau^{avg} is the average rate.  Then perhaps the marginal rate is set at the statutory rate and the average is adjusted to hit a target corp income tax revenue/gdp target.

**Comment by salimfurth** [comment]
Going through the math, and letting \delta^{\tau}=\delta, I think it boils down to:
tax revenue = \tau * r * K

If \delta = 0.05 and r = 0.04 in equilibrium, then the average tax rate is (4/9)*\tau, since "corporate income" in the tax is a pre-depreciation measure.

**Comment by salimfurth** [comment]
@jdebacker, the more I think about this, the less meaningful it sounds. The literature on marginal taxes is focused (appropriately) on specific projects. But in a simple representative firm model, there are no projects - capital is fungible and the Q-value is always 1. In a richer model, we would want to build in a wedge between the value of new capital versus old, which is responsive to tax law. But if all we're doing is finding complicated ways to change the distortion on capital, let's stick with your original idea. I also replicated your work, I think, in my own branch today (corporate_tax), which has a depreciation parameter as well as the statutory rate.

**Comment by jdebacker** [comment]
The suggestion I make above does not work in with a CRS production function as economic profits are zero.  Therefore, the scaling parameter for the average tax rate has no effect.

**Comment by jdebacker** [comment]
We have added the `adjustment_factor_for_cit_receipts`, which does serve the purpose of accounting for differences in marginal and average tax rates. It might be helpful to make this vary across industry (and perhaps time also).  But until then, I'm going to close this issue.

**Comment by jdebacker** [comment]
Reopening, since two things might be added to this:

1. Make the `adjustment_factor_for_cit_receipts` TxJ in dimension
2. Create to separate tax business tax rate params, e.g., `tau_b_mtr` and `tau_b_etr`
