### ISSUE TITLE
New monotone tax function estimation and Euler equation solution

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-Core#574]
We need a new functional form for our tax function estimation `tau(x,y)` that is still continuous and monotonically increasing in both labor income `x=w*n` and capital income `y=r*b`( first derivatives are everywhere positive) but relaxes the condition that the second derivatives `d2tau/dx2<0` and `d2tau/dy2<0` be everywhere negative.

The current functional form for our three types of tax functions--effective tax rates, marginal tax rates on labor income, and marginal tax rates on capital income--is the following 12-parameter function. This tax function is detailed in DeBacker, Evans, and Phillips, "[Integrating Microsimulation Models of Tax Policy into a DGE Macroeconomic Model](https://sites.google.com/site/rickecon/DeBackerEtAl2019.pdf)," *Public Finance Review*, 47:2, pp. 207-275 (Mar. 2019).
<img width="1202" alt="taxfunc_orig" src="https://user-images.githubusercontent.com/4317690/83576297-a83d9000-a4ee-11ea-96a6-1fb1ee2c23a7.png">
This functional form satisfies the constraint that the first derivatives are everywhere positive and the second derivatives are everywhere negative. It takes the standard negative exponential shape in either the `x` or the `y` direction holding the other variable constant.

With two recent tax reforms--the [Biden Plan](https://www.taxpolicycenter.org/publications/analysis-former-vice-president-bidens-tax-proposals) from Feb. 2020 and a [universal basic income (UBI)](https://en.wikipedia.org/wiki/Basic_income) proposal--that this function with its restrictions is not able to model well the characteristics of reforms that create "lumps" in the resulting tax data.

**We need to maintain the following characteristics (constraints) on our tax function of choice:**
1. `tau(x,y)` must be monotonically increasing in both `x` and `y`. This condition ensures that a unique solution exists for the household Euler equations.
2. `tau(x,y)` should be able to take on negative values for small values of `x` and `y`. Policies like the Earned Income Tax Credit (EITC) and UBI and other tax credit programs create negative effective tax rates and sometimes negative marginal tax rates at low income levels. Because of the monotonicity requirement in (1), these negative rates can only exist in our functional forms at the lowest income levels.
3. `tau(x,y)` should be a function of both labor income `x` and capital income `y` in such a way that the two variables can interact to determine the tax rate `tau`. This is something that we found to be empirically true in the [Tax-Calculator](https://github.com/PSLmodels/Tax-Calculator) data from [`get_micro_data.py`](https://github.com/PSLmodels/OG-USA/blob/master/ogusa/get_micro_data.py), which is documented in the [DeBacker, et al (2019)](https://sites.google.com/site/rickecon/DeBackerEtAl2019.pdf) paper.
4. The function should approach an asymptote as `x` or `y` gets large.

**Characteristics to change:**
5. We need to allow for the second derivatives of the tax function `d2tau/dx2` and `d2tau/dy2` to be both negative and positive. That is, the function should allow for multiple inflection points.
![taxfuncs_new](https://user-images.githubusercontent.com/4317690/83590801-ce295b80-a513-11ea-838c-ddf0f01e28bc.png)
6. As either `x` or `y` gets small, the respective second derivatives can be positive or negative and the asymptote can be either negative infinity or some finite number. This allows for policies like the EITC or UBI, which flatten out effective tax rates at the low end in addition to making them negative.

**Potential functions to try**
* Monotone linear piecewise regression over `N` areas in two dimensions (x, y). I know how to do this in one dimension. I don't know how to do it in two dimensions.
* Monotone cubic spline regression over `N` areas in two dimensions (x,y). I found a [Wikipedia article](https://en.wikipedia.org/wiki/Monotone_cubic_interpolation) showing how to constrain a univariate cubic spline interpolant (passes through all the points) to be monotone. However, it is probably a big jump to do that in two dimensions and to do it as a regression (passes through the average or some measure of fit of many points).

This function needs to be able to have its parameters estimated with data, then reproduced to get the predicted values in OG-USA. It could be nonparametric, although everything we have used up to now has been parametric (DeBacker-Evans-Phillips, Gouveia-Strauss, linear, average (constant)).

cc: @jdebacker @kerkphil

**Comment by tomrod** [comment]
On condition 4, can you give more definition to the asymptote?

**Comment by rickecon** [comment]
I received a question from @tomrod asking to clarify the proposed change in point 4 that allows for different asymptotes as `x --> 0` or as `y --> 0`. The DeBacker-Evans-Phillips functional form in OG-USA has the negative exponential shape (e.g. log utility) such that the tax rate goes to a very negative number or to -infinity as either `x --> 0` or as `y --> 0`. And the second derivatives of the function are both negative for small values of `x` and `y` (as `x --> 0` or as `y --> 0`). See the yellow and green lines below, labeled "DEP".

![Compare_ETR_functions](https://user-images.githubusercontent.com/4317690/83600931-e6f23b00-a52c-11ea-9249-ed5e2bf2aacf.png)

The univariate Gouveia-Strauss functional form in OG-USA and used broadly in the literature can have an asymptote that is less than -infinity as `x --> 0` or as `y --> 0` and the second derivatives can be positive. See the pink line in the image above. @khakieconomics suggested using normal CDF's which enforce this property, as would an arctangent function.

I see three shortcomings with the Gouveia-Strauss, normal CDF, and arctangent functional forms.
1. It is univariate, a function of only total income, and does not allow for multivariate versions.
2. It only allows for the finite asymptote as `x --> 0` or as `y --> 0` with second derivatives that are positive. It does not allow for the -infinity asymptote case with negative second derivatives.
3. It only allows for one inflection point (where the second derivative changes sign). That is better than the 0 inflection points in DEP, but reforms like the Biden plan that increases taxes at the upper end of the distribution might need up to three inflection points.

**Comment by MaxGhenis** [comment]
Using [Tibshirani et al (2011)](https://www.stat.cmu.edu/~ryantibs/papers/neariso.pdf) as a baseline for univariate isotonic regression:
![image](https://user-images.githubusercontent.com/6076111/83600767-27998680-a524-11ea-8f20-2d5328ec1de2.png)

Would it be correct to characterize (as a potential objective function) the problem as the following?
![image](https://user-images.githubusercontent.com/6076111/83601581-b3f87900-a525-11ea-9532-599a1abaf3d6.png)

If so, it seems like the Pool Adjacent Violators Algorithm (PAVA), which solves univariate isotonic regression, could be adapted to the bivariate case, e.g. by alternating between `i` and `j`. I found [this description](https://stat.fandom.com/wiki/Isotonic_regression) of PAVA helpful.

**Comment by rickecon** [comment]
@MaxGhenis. The Tibshirani, et al (2011) paper about isotonic regression is really an interpolant that passes through all the points except when the constraint `beta_1<=beta_2<=...beta_n`. You see this because there are `n` data points `{y_n}` and `n` estimated betas `{beta_n}`. I found some JavaScript code in this [Wikipedia article](https://en.wikipedia.org/wiki/Monotone_cubic_interpolation) that shows how to make the monotone interpolation that you describe in your first equation and which monotone estimation I think is described in your optimization problem. But I want a regression version of this problem. I want a functional form where the number of betas is less than the number of data points.

Another way to see my point is to think of the univariate case, like the first one you mention in the previous comment. Each of the betas defines a line between adjacent betas. Two regression versions of this problem are defined in the two alternatives I list at the beginning of this issue (piecewise linear regression and cubic spline regression). There is good code to do this in the univariate case for an interpolation problem. It would take some easy tweaking for the regression in the univariate case. I think it is much more complicated in the bivariate case.

**Comment by tyleransom** [comment]
What you drew in step 5 looks almost like a set of piecewise log functions. But I guess this function needs to be everywhere twice differentiable, so that wouldn’t work? I’m wondering if there is a way to smooth out the transition points.

**Comment by tomrod** [comment]
Would some form of wave in the positive orthant suffice, followed by controlled behavior when x or y fall below 0?

**Comment by MaxGhenis** [comment]
@rickecon could you share sample data to work through?

I only cited the Tibshirani paper for the description of isotonic regression, agree that their approach is unsuitable.

**Comment by rickecon** [comment]
* Aaron Hedlund suggested looking at Mariacristina De Nardi's and Gustavo Ventura's use of parameterized tax functions.
* Len Burman suggested higher order polynomials which are extremely flexible. But the higher order the polynomial, the harder to estimate the function given the constraints (monotonicity and an asymptote as x or y get large). The polynomial coefficients might be underidentified, making estimation have multiple solutions. Take a cubic (third order) polynomial example. The first derivative is a second order polynomial. Enforcing that a parabola be everywhere positive on the range of the polynomial is doable but hard. And it gets even harder as the order of the polynomial increases. Len suggested a bounding strategy for the polynomial functions that maintains continuity of making the function a(x)*p(x) + (1-a(x)*B, where a(x) is the weight, p(x) is the polynomial, and B is a constant. a(x) is a continuous differentiable function on [0,1]. And lim a(x) = 0. E.g., a(x) = 2/(1+exp(kx)), where k>0, has a(0) = 1 and a(inf) = 0. You could apply the a similar bounding method for negative values. This latter approach is using the logistic function is what we already to in the DEP functional form in OG-USA. The weakness of that approach is that it doesn't fit well the tax policies that flatten out the low income end of the tax rate function (like a normal cdf or arctan; think EITC or UBI).
*  @baogorek suggested adding a penalties to 1st and 2nd derivatives using splines via `optim` in R. This is probably the right way to do a high order polynomial with constraints.

**Comment by rickecon** [comment]
@tyleransom . I don't think the function has to be everywhere differentiable. It just has to be continuous. The derivatives need not be continuous.

For example, back in the day, Ken Judd taught me how to convexify an optimization problem with `N` finite segments of a function. Think single period static consumption optimization problem with a step function for marginal tax rates over `N` income brackets. The problem is convex on each of those income brackets. You convexify the problem by, instead of optimizing over the hard problem and choosing just `c`, set up the problem to choose `N` weights `{w_n}` and `N` consumptions `{c_n}` on each bracket to maximize utility. This is analogous to creating lotteries over each income segment. The solution will be to have the weight of the optimal solution equal 1 and all the other weights equal 0. The optimal consumption is the `c_n` that corresponds to the weight that equals 1.

So piecewise linear might work here. If continuity is valuable, then piecewise cubic spline regression might be the answer.

**Comment by rickecon** [comment]
@tomrod Can you expand on this wave in the positive orthant? What is the functional form? How do I constrain it to be monotonically increasing and have the property that it asymptotes for large income levels `x --> infty` and `y --> infty`?

**Comment by rickecon** [comment]
@MaxGhenis I really like the Tibshirani, et al (2011) paper. I just need to adjust it to the regression version (fitting an average of points) rather than passing through as many as possible subject to constraints--even though they title their approach regression. This is an approach that I am most optimistic about. My only worry is that it will be an order of magnitude harder in two dimensions. But @khakieconomc 's suggestion of just convolving univariate functions with weights is a good one. That is essentially what we do with our DEP functional form.

**Comment by rickecon** [comment]
@MaxGhenis I will post some data later today as a testing ground for these functions. I will take this data from the [Tax-Calculator](https://github.com/PSLmodels/Tax-Calculator) output generated in the [get_micro_data.py](https://github.com/PSLmodels/OG-USA/blob/master/ogusa/get_micro_data.py) module of OG-USA. These data will look like the scatterplot in this figure. Time to start experimenting. I will document the progress in this issue. Anyone should feel free to contribute and/or comment.

**Comment by rickecon** [comment]
Len Burman made an interesting comment about the monotonicity requirement of the tax functions that made me think about this. We decouple the estimation of the marginal tax rate functions from the effective tax rate functions in OG-USA because there are policies that can change effective tax rates and not change marginal tax rates (e.g. certain types of tax credits). The marginal tax rate functions are the only things that show up directly in the Euler equations. As such, I think that means that only our marginal tax rate functions have to have strict monotonicity imposed. And I think we could get away some nonmonotonicity in the effective tax rate function that only enters into the budget constraint. @jdebacker does this sound correct to you?

**Comment by tomrod** [comment]
Thinking more in a design in the f(x, y) space that satisfies what you're looking to do. Picture of (x, z) projections of what you're looking to build as I understand it. 

![2020-06-03 12 20 24](https://user-images.githubusercontent.com/1719700/83667828-a201ef00-a594-11ea-8517-0c90d37080b5.jpg)

**Comment by tomrod** [comment]
Apologies for the picture rotation, not sure how to change on github's mobile website.

**Comment by MaxGhenis** [comment]
Here's R code for multiple isotonic regression, written by Meyer, an apparent expert on isotonic regression: https://www.stat.colostate.edu/~meyer/multipleiso.htm

[Meyer (2013)](https://www.tandfonline.com/doi/pdf/10.1080/03610918.2012.659820) shows this relevant diagram:
![image](https://user-images.githubusercontent.com/6076111/83714880-e31ff080-a5e0-11ea-943d-0ed9bfc5d98b.png)

Meyer is also a coauthor on [Wu et al (2014)](https://www.sciencedirect.com/science/article/abs/pii/S0378375814002055) "Penalized Isotonic Regression," which is an adaptation we may want to consider.
![image](https://user-images.githubusercontent.com/6076111/83714975-28442280-a5e1-11ea-9dc7-5e89b6f44c20.png)

**Comment by jdebacker** [comment]
In addition to the choice of functional form, others, such as @jpycroft and @benrpage1, have noted the following considerations in the estimation:
1. The statistical objective function and distance norm used (e.g., mean square errors or mean absolute difference).
2. The optimizer used to estimate the parameters (e.g., a global maximization algorithm vs. gradient based methods).
3. Identifying where the function's fit is better or worse (e.g., are errors larger for high income filers or low income filers?).    One could perhaps consider changing the weights applied to errors to target a better fit on particular part of the function.
