### ISSUE TITLE
Model UBI directly rather than through ETRs

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-Core#626]
Per this week's discussion, this could avoid irregularities we're observing on the ETR side. UBI could instead be added to the transfers, or added as its own element. It could start as a flat amount per tax unit, and could be enhanced by multiplying by a grid of average number of people per age group (<18, 18-20, 21-64, 65+, to align with taxcalc) by filing unit `s,j`.

**Comment by jdebacker** [comment]
@MaxGhenis I like this idea and do not think it would be too difficult to incorporate.

**Comment by rickecon** [comment]
This issue was resolved by PR #715.
