### ISSUE TITLE
Add Forbes 400 to SCF for calibrating initial wealth distribution

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-Core#638]
The [SCF codebook](https://www.federalreserve.gov/econres/files/codebk2010.txt) states:
>By design, the SCF sample excludes people who are included in the Forbes Magazine list of the 400 wealthiest people in the U.S. (see references in "SAMPLE DESIGN" above).  However, there are several reasons why respondents with wealth at this level could appear in the sample anyway.  In the 2010 survey, there were 10 observations that had net worth at least equal to the minimum level needed to qualify for the Forbes list.  Because it would be very difficult to obscure sufficiently the identity of such people without rendering their data virtually useless, it was decided to remove them from the public version of the data set. Thus, the public version of the data set contains 6,482 of the 6,492 observations in the full data set.

From [PWBM (2019)](https://budgetmodel.wharton.upenn.edu/issues/2019/12/12/senator-elizabeth-warrens-wealth-tax-projected-budgetary-and-economic-effects):
>PWBM’s wealth tax model uses data from the Survey of Consumer Finances (SCF), a high-quality survey of American households’ assets and liability holdings. The SCF oversamples high net worth households to ensure adequate detail on the top of the wealth distribution. The SCF is conducted every three years, so the most recently available survey is from 2016. The survey excludes the 400 richest Americans for confidentiality reasons, making it necessary to augment the survey with net worth data from the Forbes 400 in order to reflect total wealth in the economy.

[CBO (2016)](https://www.cbo.gov/sites/default/files/114th-congress-2015-2016/reports/51846-familywealth.pdf) also added the Forbes 400 to the SCF, and several other academic studies do the same.

The [2019 Forbes list](https://www.forbes.com/forbes-400/) looks pretty easy to extract into a spreadsheet, and it also has each person's age.

**Comment by jdebacker** [comment]
This has been moved to the OG-USA repo, [Issue #47](https://github.com/PSLmodels/OG-USA/issues/47).
