### ISSUE TITLE
Restructure handling of tax function estimation and parameters

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-Core#699]
I'm opening this issue to discuss how we might change the handling of the tax function estimation routines and the handling of the tax function parameter estimates.

Before laying out a particular approach, I want to note some goals of such a refactoring:
1. A move of the tax function estimation out of OG-USA and into the OG-USA-Calibration model (to facilitate the move to a more country-agnostic OG model).
2. Easier interfacing between OG-USA with different microsimulation model outputs  (related to (1)).
3. Improved ability to use cached parameter estimates on Compute Studio and elsewhere to avoid re-estimating parameters for baseline policy.
4. Reduce depending on pickle files for storing cached parameter estimates on the repo (related to (3)).

cc @rickecon

**Comment by rickecon** [comment]
@jdebacker. I propose that we close this Issue when PR #819 is merged.
