### ISSUE TITLE
Installation issues via `pip`

### ISSUE THREAD

**Issue by nikhilwoodruff** [PSLmodels/OG-Core#732]
Just opening this in the case that anyone else has had this issue, though I suspect it could to be a hardware issue so feel free to close.

When I run `pip install git+https://github.com/PSLmodels/OG-USA`, I get:

```console
(base) nikhil@nikhil-pc:~/pslmodels$ gh repo clone PSLmodels/OG-USA
Cloning into 'OG-USA'...
remote: Enumerating objects: 26835, done.
remote: Counting objects: 100% (977/977), done.
remote: Compressing objects: 100% (279/279), done.
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
exit status 128
```

[I've](https://stackoverflow.com/questions/38378914/how-to-fix-git-error-rpc-failed-curl-56-gnutls) [tried](https://stackoverflow.com/questions/60019906/error-rpc-failed-curl-56-gnutls-recv-error-110-the-tls-connection-was-non) [all](https://stackoverflow.com/questions/48035434/git-error-rpc-failed-curl-56-gnutls-recv-error-54-error-in-the-pull-functi) [these](https://sarathblogs.blogspot.com/2017/02/solved-fix-for-git-clone-failure-due-to.html) [solutions](https://stackoverflow.com/questions/6842687/the-remote-end-hung-up-unexpectedly-while-git-cloning), and the only thing that worked was by using:

`git clone https://github.com/PSLmodels/OG-USA --depth 1 && cd OG-USA && pip install .`

Which seems to work, though I still have issues solving in OG-UK, so conscious this might be a potential cause.

**Comment by jdebacker** [comment]
@nikhilwoodruff That looks like an issue with the repo being too large for Git.  I've had something similar in another repo and one thing that helped was to change your buffer size.  e.g., 

```
git config --global http.postBuffer 1048576000
```

**Comment by nikhilwoodruff** [comment]
Thanks @jdebacker - unfortunately I tried that, and a few variations, and still got the same error:

```console
(base) nikhil@nikhil-pc:~/pslmodels$ git config --global http.postBuffer 1048576000 && pip install git+https://github.com/PSLmodels/OG-USA
Collecting git+https://github.com/PSLmodels/OG-USA
  Cloning https://github.com/PSLmodels/OG-USA to /tmp/pip-req-build-u132vknd
  Running command git clone -q https://github.com/PSLmodels/OG-USA /tmp/pip-req-build-u132vknd
  error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
  fatal: the remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
WARNING: Discarding git+https://github.com/PSLmodels/OG-USA. Command errored out with exit status 128: git clone -q https://github.com/PSLmodels/OG-USA /tmp/pip-req-build-u132vknd Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q https://github.com/PSLmodels/OG-USA /tmp/pip-req-build-u132vknd Check the logs for full command output.

```

**Comment by nikhilwoodruff** [comment]
This doesn't seem to have happened (probably just my own previous network conditions) for a while, so closing.
