### ISSUE TITLE
OG-Core logo

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-Core#735]
We should create an OG-Core logo.  My suggestion is to use the OG-USA logo, but without the flag-filled bubbles (i.e., all bubbles are empty).

@rickecon thoughts?

**Comment by rickecon** [comment]
@jdebacker. Let me play with this.

**Comment by rickecon** [comment]
@jdebacker How about this? I put a small circle, a "core", with some mild color in the place where the flag is in the country models. Very understated, but still fits with the broad theme.
![OG-Core_logo](https://user-images.githubusercontent.com/4317690/126518430-7d84603d-dbcc-44ea-a06b-580e1e153415.png)

**Comment by jdebacker** [comment]
@rickecon Thanks for taking a stab at this.  Can you show me what it might look like with the circle all the way filled in?  At it is, it's reminding me of a certain part of the human anatomy.

**Comment by rickecon** [comment]
@jdebacker. Here is the logo with the entire circle filled in. I think I still like the previous logo better because it looks like a core.
![OG-Core_logo2](https://user-images.githubusercontent.com/4317690/126834593-82abdee4-a24e-4cc5-822e-a09117bb1947.png)

**Comment by rickecon** [comment]
@jdebacker. This is what I am thinking about when I say I like the first logo. I like the little core circle that doesn't quite fill up the entire outer circle. That points the mind more to the "core" concept in my opinion. Although you are saying that it looks like the Hooters logo. I am happy to go with either one.

<img width="1203" alt="Screen Shot 2021-07-26 at 4 18 44 PM" src="https://user-images.githubusercontent.com/4317690/127066478-d68be2f1-ac12-4ac1-9438-541b9dd10c85.png">

**Comment by rickecon** [comment]
@jdebacker. Here is what my recommended `OG-Core_logo_long.png` looks like. Note the change in the wording below the image. Let me know if you want anything different there as well.
![OG-Core_logo_long](https://user-images.githubusercontent.com/4317690/127067112-0fe936a9-cf9a-4d2b-80c6-df9ae331f60f.png)

**Comment by rickecon** [comment]
It looks like this issue is done. Closing.
