### ISSUE TITLE
Question about budget closure rule

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/OG-Core#783]
The documentation says this:

<img width="1302" alt="Screen Shot 2022-02-10 at 9 39 25 AM" src="https://user-images.githubusercontent.com/12170745/153430368-f2af68df-b197-4f1a-86cf-df3f0e370190.png">

Which model specification parameter do I use to switch from option 1 to option 2?

**Comment by rickecon** [comment]
@martinholmer. We don't currently have the functionality to do option 2 or 3 for a closure rule. The only stabilization policy (closure rule) right now in `OG-Core` or any of its country calibrations is to change `G_t` to hit a long-run debt-to-GDP ratio. I will update the documentation to reflect the "in-process" nature of options 2 and 3. Thanks for catching that.

However, you can flexibly change the date at which the closure rule begins `tG1`, the date at which the closure rule is forced to exactly hit the long-run debt-to-GDP ratio `tG2`, and the rate of convergence `rho_G` to the long-run debt-to-GDP ratio between dates `tG1` and `tG2`.

**Comment by martinholmer** [comment]
@rickecon said:
 > We don't currently have the functionality to do option 2 or 3 for a closure rule. The only stabilization policy (closure rule) right now in OG-Core or any of its country calibrations is to change G_t to hit a long-run debt-to-GDP ratio. I will update the documentation to reflect the "in-process" nature of options 2 and 3. Thanks for catching that.

OK, thanks for the clarification.

**Comment by martinholmer** [comment]
@rickecon said:
> However, you can flexibly change the date at which the closure rule begins tG1, the date at which the closure rule is forced to exactly hit the long-run debt-to-GDP ratio tG2, and the rate of convergence rho_G to the long-run debt-to-GDP ratio between dates tG1 and tG2.

But none of these three parameters will change the steady-state equilibrium, right? 
If I'm wrong about that, please explain.

**Comment by rickecon** [comment]
@martinholmer. You are right that the parameters `tG1`, `tG2`, and `rho_G` do not influence whether or not the steady state solves. However, the long-run assumption about the debt-to-GDP ratio `alpha_D` in the documentation (`debt_ratio_ss` in the model) does matter for the steady state.

**Comment by rickecon** [comment]
This issue is resolved by PR #784. Closing.
