### ISSUE TITLE
Use black for code formatting

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-Core#804]
We've talked about using `black` for code formatting, but hesitated because it might affect the git blame.  However, it now appears that [GitHub can ignore commits in the blame view](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view).

Shall we make the switch?

cc @rickecon @MaxGhenis @nikhilwoodruff

**Comment by nikhilwoodruff** [comment]
Nice find - I'd favour using `black`. Just a thought though - do we definitely know it'd affect the blame that much? If each person uses black, maybe it wouldn't really obstruct it - I've just started using the GitLens extension in VS Code and not found many obvious "this git blame is just one big formatting change" files.

**Comment by jdebacker** [comment]
To clarify - I agree that on going use of `black` won't be a problem - I would propose just reformatting the whole repo in one commit - and ignoring that commit.  So the existing blame is in tact.  Then all future changes (including formatting with black) are including in the blame from then on.

**Comment by rickecon** [comment]
@nikhilwoodruff's comments provide support for reformatting the whole repo with `black` even if it influences the `git blame` (as long as it doesn't influence it that much). I agree wholeheartedly with reformatting the repo with `black`. And I especially think it is a great idea if we can ignore the one commit that reformats the whole thing. Then we can put a CI test for `black` formatting. Great find @jdebacker.

**Comment by jdebacker** [comment]
Addressed with PR #805
