### ISSUE TITLE
Intel mkl dependency may break the installation for ARM Macs

### ISSUE THREAD

**Issue by SeaCelo** [PSLmodels/OG-Core#821]
ARM Macs cannot use the Intel MKL library. Other libraries are available. See for example this comment thread: https://developer.apple.com/forums/thread/695963. 

The installation of OG-CORE requires this MKL library in two places: environment.yml and setup.py
This seems (not confirmed) to be breaking the installation for Macs running the ARM chips (M1, M2). 
#### There are two ways to getting around this for now. 

*First, make sure you installed anaconda correctly (I prefer miniforge). See links below for some help. 

*Second: 
A) line 8 of environment.yml should be commented if you are running ARM Mac. 
B) setup.py introduced the package dependency requirement of 'mkl' in this commit: [https://github.com/PSLmodels/OG-Core/commit/4a09c5d1a27946af941038a3a8526ddde92c6dc3](url) 

PS: If you have an M1 Mac you should be installing anaconda for the right architecture. Some (older) guides:
[https://www.youtube.com/watch?v=w2qlou7n7MA](url)
[https://towardsdatascience.com/how-to-easily-set-up-python-on-any-m1-mac-5ea885b73fab](url)
[https://stackoverflow.com/questions/65534042/anaconda-and-upgrading-to-new-m1-mac](url)

**Comment by rickecon** [comment]
@SeaCelo. Can you post the error message you are getting? Or maybe you've already fixed it. I have not run into this problem on my machine (MacBook Pro, Apple M1 Max Chip). Our recommended installation steps are the following:
1. Install the Anaconda distribution of Python
  * If already installed, make sure:
    * your conda package manager is up-to-date: `conda update conda`
    * the Anaconda distribution of Python is up-to-date: `conda update anaconda`
2. Create or update the `ogcore-dev` conda environment
  * If creating the environment, navigate to the `OG-Core` directory on your local machine in your terminal (Mac and Linux) or Anaconda prompt (Windows) and type `conda env create -f environment.yml`
  * If updating the environment, I recommend removing the existing environment `conda remove --name ogcore-dev --all` and installing it new `conda env create -f environment.yml`
3. Activate the new `ogcore-dev` conda environment by typing `conda activate ogcore-dev` and add the `ogcore` package to that environment by typing `pip install -e .` in your terminal or Anaconda prompt window in the top `OG-Core` directory.

You can now test whether this works by being in your terminal or Anaconda prompt and having the `ogcore-dev` conda environment active and typing `python ./run_examples/run_ogcore_example.py`.

After completing these steps, everything should be set up on your machine to run `OG-Core`. We have tested this on Mac, Windows, and Linux. Let me know if you still have problems running `OG-Core` after completing these steps.

**Comment by rickecon** [comment]
@jdebacker and @SeaCelo. I am currently running time and run tests of the `run_ogcore_example.py` script for the specifications in the table below. In particular, I am testing the performance of the model with and without the `mkl` for operating systems Mac OSx (both M1 and non M1 Anaconda distribution), Windows, and Linux. I want to try to get rid of the `mkl` dependency, which causes problems with the Anaconda M1 distribution of Python. [I am currently running these and filling out the rows.]

| OS   | Python | Cores | SciPy |     mkl      | Baseline | Reform | Tests pass  | Tests time |
| :---- | :------: | :----: | :-----: | :-------: | :-------: | :------: | :---------: | :---------: |
| OSx | 3.10.8    |     7    |  1.9.3  | 2022.2.1 | 1802.11  | 1908.19 | 1 failed     | 15804.63  |
| OSx |       ?      |     7    |  ?        |    none    |                |                |                 |                    |
| OSx |    ? (M1) |     7    |  ?        |   ?           |                |                |                 |                    |
| OSx |    ? (M1) |     7    |  ?        |   none    |                |                |                 |                    |
| Windows |    ?  |     7    |  ?        |   ?           |                |                |                 |                    |
| Windows |    ?  |     7    |  ?        |   none    |                |                |                 |                    |
| Linux |    ?  |     7    |  ?        |   ?           |                |                |                 |                    |
| Linux |    ?  |     7    |  ?        |   none    |                |                |                 |                    |

**Comment by SeaCelo** [comment]
@rickecon Please also check Activity Monitor when running the test. Depending on how I installed Python it would report either `Intel` or `Apple` under "Kind". As far as I can tell there is no easy way to ask Python to self-report its build architecture. That is the only way I found to check if Python is running under Rosetta.

This had a large performance delta in my tests:

| OS | Python  |       Cores | SciPy    | math library | Baseline + Reform (mins) |
| ----- | ------------ | ---- | ---------| --------------| -------| 
| OSX | 3.9.12 ARM | 8+2 | 1.9.3    |  "openblas"     | 36.29 |
| OSX | 3.9.12 ARM | 8+2 | 1.9.3    |  "accelerate"    | 37.00 |
| OSX | 3.9.12 **Intel**  | 8+2 | 1.9.3    |  "mkl"      | **59.29** |

**Comment by SeaCelo** [comment]
Linking to the discussion that explains the issue and a work around. https://github.com/EAPD-DRB/OG-ZAF/issues/15#issue-1443077906
