### ISSUE TITLE
Remove surv_rate object

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-Core#885]
The survival rates object `surv_rate` parameter in `OG-Core` is incorrectly specified in that it is currently just an $S$-element list (see `default_parameters.json`). It would need to be a nested (2-dimensional) $S$-element list to be consistent with the mortality rates `rho` parameter, immigration rates, and population parameters. However, `surv_rate` is only used in `parameters.py` in `OG-Core`, and it shows up in testing input objects such as `testing_params.json` and `create_params_inputs.pkl`.

We propose that we make the following changes to `OG-Core`:
* Remove the `surv_rate` object from `default_parameters.json`
* Recode line 578 of `parameters.py` so that `surv_rate` is just equal to 1 - `rho`. This way `surv_rate` does not have to come from  a country calibration `demographics.py`.
* Fix the tests that depend on `surv_rate` being present.

This will require similar changes to be made to the country calibrations (e.g., OG-USA, OG-ZAF):
* Update the `rho` parameter in `og[cntry]_default_parameters.json`
* Remove the `surv_rate` parameter in `og[cntry]_default_parameters.json`
* Remove `surv_rate` from the output of `demographics.py`

cc: @jdebacker

**Comment by jdebacker** [comment]
Resolved with PR #886
