### ISSUE TITLE
Remove Python 3.9 tests

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-Core#924]
I propose that we follow a general rule across all the OG modeling repositories to run our `build_and_test.py` CI tests on all operating systems (OG-USA currently is not working on the Windows tests) and across only the two most recent versions of Python on which the code is being tested.

For example, for OG-Core, which is currently tested on Python 3.9, 3.10, and 3.11 but not on Python 3.12 yet (see Issue #889), we would change the `build_and_test.py` python matrix to just Python 3.10 and 3.11, dropping the 3.9 tests. And once we got the tests passing on Python 3.12, we would drop the Python 3.10 tests and only test on Python 3.11 and 3.12.

Let me know what you think about this approach.

cc: @jdebacker debacker

**Comment by jdebacker** [comment]
@rickecon I agree.
