### ISSUE TITLE
Change the validation requirements on wealth tax parameters

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-Core#989]
The OG-Core specification of household wealth tax liability $T^w_{j,s,t}$ is an effective tax rate $\tau^{etr,w}_{j,s,t}$ multiplied by the household's wealth $b_{j,s,t}$.

$$ T = \tau b = p\left(\frac{h b}{h b + m}\right)b $$

The wealth tax effective tax rate is $p\left(hb/[hb+w]\right)$. This effective tax rate is a function of wealth $b_{j,s,t}$. This allows for both progressive wealth tax rates ($h^w, m^w > 0) and flat tax rates ($m^w=0). However, the parameters in the function are currently specified `default_parameters.json` in a way that does not allow for a pure flat wealth tax. 

The current specification is for $m^w>0$ and $h^w\geq 0$. This does not allow for a flat tax. I recommend we change the valid ranges for two of the wealth tax parameters, allowing `m_wealth` to be zero, and forcing `h_wealth` to be positive.

I updated the language in the wealth tax section of `government.md` documentation to reflect this change, but I have not yet changed it in the code.

cc: @jdebacker

**Comment by jdebacker** [comment]
Addressed in PR #995
